name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build MarvelDemo iOS App
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v3

      - name: 🧹 Clean DerivedData (optional safety)
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: 🛠 Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app


      - name: 🏗 Build App (No Code Signing)
        run: |
          cd MarvelDemo
          xcodebuild clean build \
            -project MarvelDemo.xcodeproj \
            -scheme Marvel \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO

      # Optional: Run unit tests
      # - name: ✅ Run Unit Tests
      #   run: |
      #     cd MarvelDemo
      #     xcodebuild test \
      #       -project MarvelDemo.xcodeproj \
      #       -scheme MarvelDemo \
      #       -destination 'platform=iOS Simulator,name=iPhone 14'

